[package]
name = "plugin-mojitos-c"
version = "0.1.0"
edition = "2021"

[dependencies]
alumet = { version = "0.7.0", path = "../alumet" }
anyhow = "1.0.95"
humantime-serde = "1.1.1"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }

[lints]
workspace = true

[build-dependencies]
bindgen = "0.71.1"
