/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn clean();
}
unsafe extern "C" {
    pub fn init(argc: ::std::os::raw::c_int, argv: *mut *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn get_labels() -> *mut *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn get_values() -> *const u64;
}
