/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    #[doc = " @brief Cleans mojitos' state, freeing everything.\n"]
    pub fn clean();
}
unsafe extern "C" {
    #[doc = " @brief Initializes mojitos's state. The get_* are ready to be called immediately after this.\n\n @param argv arguments to be passed to mojitos. MUST BE ONLY MOJITOS ARGUMENTS, not including argv[0] (you can pass argv + 1 or &argv[1] from your main)\n @return the number of metrics registered. This will be the size of arrays returned by get_* functions."]
    pub fn init(argv: *mut *mut ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    #[doc = " @brief Get the labels of the metrics measured as an array of strings\n\n @return char**"]
    pub fn get_labels() -> *mut *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    #[doc = " @brief Makes all measurements and returns an array of values.\n\n @return const uint64_t*"]
    pub fn get_values() -> *const u64;
}
