
typedef struct CounterOption{
    char *name;
    __u32 perf_type;
    __u64 perf_key;
} CounterOption;

static CounterOption perf_static_info[] = {
    { .name = "cpu_cycles", .perf_type = PERF_TYPE_HARDWARE, .perf_key = PERF_COUNT_HW_CPU_CYCLES},
    { .name = "instructions", .perf_type = PERF_TYPE_HARDWARE, .perf_key = PERF_COUNT_HW_INSTRUCTIONS},
    { .name = "cache_references", .perf_type = PERF_TYPE_HARDWARE, .perf_key = PERF_COUNT_HW_CACHE_REFERENCES},
    { .name = "cache_misses", .perf_type = PERF_TYPE_HARDWARE, .perf_key = PERF_COUNT_HW_CACHE_MISSES},
    { .name = "branch_instructions", .perf_type = PERF_TYPE_HARDWARE, .perf_key = PERF_COUNT_HW_BRANCH_INSTRUCTIONS},
    { .name = "branch_misses", .perf_type = PERF_TYPE_HARDWARE, .perf_key = PERF_COUNT_HW_BRANCH_MISSES},
    { .name = "bus_cycles", .perf_type = PERF_TYPE_HARDWARE, .perf_key = PERF_COUNT_HW_BUS_CYCLES},
    { .name = "ref_cpu_cycles", .perf_type = PERF_TYPE_HARDWARE, .perf_key = PERF_COUNT_HW_REF_CPU_CYCLES},
    { .name = "cache_l1d_r_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_L1D | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_l1d_r_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_L1D | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_l1d_w_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_L1D | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_l1d_w_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_L1D | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_l1d_p_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_L1D | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_l1d_p_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_L1D | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_ll_r_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_LL | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_ll_r_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_LL | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_ll_w_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_LL | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_ll_w_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_LL | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_ll_p_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_LL | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_ll_p_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_LL | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_dtlb_r_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_DTLB | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_dtlb_r_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_DTLB | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_dtlb_w_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_DTLB | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_dtlb_w_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_DTLB | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_dtlb_p_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_DTLB | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_dtlb_p_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_DTLB | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_itlb_r_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_ITLB | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_itlb_r_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_ITLB | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_itlb_w_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_ITLB | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_itlb_w_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_ITLB | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_itlb_p_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_ITLB | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_itlb_p_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_ITLB | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_bpu_r_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_BPU | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_bpu_r_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_BPU | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_bpu_w_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_BPU | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_bpu_w_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_BPU | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_bpu_p_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_BPU | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_bpu_p_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_BPU | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_node_r_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_NODE | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_node_r_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_NODE | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_node_w_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_NODE | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_node_w_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_NODE | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_node_p_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_NODE | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_node_p_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_NODE | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_op_read_r_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_READ | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_op_read_r_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_READ | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_op_read_w_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_READ | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_op_read_w_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_READ | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_op_read_p_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_READ | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_op_read_p_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_READ | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_op_prefetch_r_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_PREFETCH | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_op_prefetch_r_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_PREFETCH | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_op_prefetch_w_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_PREFETCH | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_op_prefetch_w_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_PREFETCH | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_op_prefetch_p_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_PREFETCH | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_op_prefetch_p_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_OP_PREFETCH | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_result_access_r_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_RESULT_ACCESS | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_result_access_r_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_RESULT_ACCESS | (PERF_COUNT_HW_CACHE_OP_READ >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_result_access_w_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_RESULT_ACCESS | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_result_access_w_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_RESULT_ACCESS | (PERF_COUNT_HW_CACHE_OP_WRITE >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cache_result_access_p_a", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_RESULT_ACCESS | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_ACCESS >> 16) },
    { .name = "cache_result_access_p_m", .perf_type = PERF_TYPE_HW_CACHE, .perf_key = PERF_COUNT_HW_CACHE_RESULT_ACCESS | (PERF_COUNT_HW_CACHE_OP_PREFETCH >> 8) | (PERF_COUNT_HW_CACHE_RESULT_MISS >> 16) },
    { .name = "cpu_clock", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_CPU_CLOCK},
    { .name = "task_clock", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_TASK_CLOCK},
    { .name = "page_faults", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_PAGE_FAULTS},
    { .name = "context_switches", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_CONTEXT_SWITCHES},
    { .name = "cpu_migrations", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_CPU_MIGRATIONS},
    { .name = "page_faults_min", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_PAGE_FAULTS_MIN},
    { .name = "page_faults_maj", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_PAGE_FAULTS_MAJ},
    { .name = "alignment_faults", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_ALIGNMENT_FAULTS},
    { .name = "emulation_faults", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_EMULATION_FAULTS},
    { .name = "dummy", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_DUMMY},
    { .name = "bpf_output", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_BPF_OUTPUT},
    { .name = "cgroup_switches", .perf_type = PERF_TYPE_SOFTWARE, .perf_key = PERF_COUNT_SW_CGROUP_SWITCHES},
};

static unsigned int nb_counter_option = 74;
